name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }

points = [ { x = 1, y = 2, z = 3 },
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]

nested = {
  a = {
    x = 1,
    y = 2,
    z = 3
  },
  b = {
    # comment
    x = 5,
    y = 6,
    z = 7
  },
  c = [
    # comment
    8, 9]
}
