[empty]
double_quote=""
single_quote=''
multi_line="""
"""

[zero]
double_quote="0"
single_quote='0'
multi_line="""
0"""

[one]
double_quote="1"
single_quote='1'
multi_line="""
1"""

[two]
double_quote="2"
single_quote='2'
multi_line="""
2"""
